# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo Hello, world! Jpb-1
    displayName: 'Run: Job-1'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Hello, world! Job-2
    displayName: 'Run: Job-2'

- job: Job3
  dependsOn: Job2
  steps:
  - script: echo Hello, world! Job-3
    displayName: 'Run: Job-3'
