
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: buildJar
    steps:
      - bash: echo mvn clean install package
- stage: dockerImage
  jobs:
  - job: buildDockerImage
    steps:
      - bash: echo docker build -t dasari508201/dear-comrade-cloud-config:0.0.1 .
  - job: pushDockerImage
    steps:
      - bash: echo docker push dasari508201/dear-comrade-cloud-config:0.0.1
- stage: deployDev
  jobs:
  - job: gcpDeployment
    steps:
      - bash: kubectl  


