trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: defaultVariableSyetemInfo
    steps:
      - bash: echo mvn clean install package $(SERVER_PORT)
      - bash: echo $(Build.BuildNumber)
      - bash: echo $(Build.BuildId)
      - bash: echo $(Build.SourceBranchName)
      - bash: echo $(Build.SourcesDirectory)
      - bash: echo $(Build.SourcesDirectory)
      - bash: echo $(System.DefaultWorkingDirectory)
      - bash: echo $(Build.ArtifactStagingDirectory)
      - bash: ls -R $(System.DefaultWorkingDirectory)
      - bash: java -version
      - bash: node --version
      - bash: python -version
      - bash: mvn -version


