# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildbuildJar
  displayName: Build buildJar
  jobs:
    - job: mavenBuild
      displayName: mavenBuild
      steps:
        - script: mvn clean install
- stage: Build
  dependsOn: BuildbuildJar
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dear-comrade-docker-hub'
        repository: 'dasari508201/dear-comrade-cloud-config'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
