apiVersion: apps/v1
kind: Deployment
metadata:
  name: dear-comrade-cloud-config
spec:
  selector:
    matchLabels:
      app: dear-comrade-cloud-config
  template:
    metadata:
      labels:
        app: dear-comrade-cloud-config
    spec:
      containers:
      - name: dear-comrade-cloud-config
        image: dasari508201/dear-comrade-cloud-config:0.0.8
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888


---
apiVersion: v1
kind: Service
metadata:
  name: dear-comrade-cloud-config
  
spec:
  type: LoadBalancer
  selector:
    app: dear-comrade-cloud-config
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  